In [ ]:
from __future__ import print_function
import pandas as pd
import numpy as np
import sqlalchemy
from datetime import datetime
import tensorflow as tf

f =  open('d:\\/stock_prediction with LSTM_version-1.txt', 'a')
print("===== Stock Prediction with LSTM_first =====", file = f)
print("start_day: {}\n".format(datetime.now()),file = f)

tf.set_random_seed(777)  # reproducibility
tf.reset_default_graph()

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

engine = sqlalchemy.create_engine('mysql+pymysql://kkang:leaf2027@localhost/stock?charset=utf8',encoding='utf-8')
    
name = input('주식이름을 입력하세요 : ')
date = input("날짜를 입력하세요 sample: '2019-01-10':")
        
select_query = "select * from market where Name= "
date_query = "Date > "

var = select_query +"'"+name+"'"+" "+"&&"+" "+date_query+"'"+date+"'"

df = pd.read_sql(var ,engine)
df = df[['Open','High','Low','Volume','Close']]

xy = df.values

seq_length = 5
data_dim = 5
hidden_dim = 10
output_dim = 1
learning_rate = 0.01
iterations = 900

test_min = np.min(xy, 0)
test_max = np.max(xy, 0)
test_denom = test_max - test_min

dataset = MinMaxScaler(xy)

train_size = int(len(xy) * 0.7)
train_set = dataset[0:train_size]
test_set = dataset[train_size - seq_length:]  # Index from [train_size - seq_length] to utilize past sequence
last_set = dataset[-seq_length:,:]

# build datasets
def build_dataset(time_series, seq_length):
    dataX = []
    dataY = []
    for i in range(0, len(time_series) - seq_length):
        _x = time_series[i:i + seq_length, :]
        _y = time_series[i + seq_length, [-1]]  # Next close price
        print(_x, "->", _y)
        dataX.append(_x)
        dataY.append(_y)
    return np.array(dataX), np.array(dataY)

trainX, trainY = build_dataset(train_set, seq_length)
print("#"*100)
testX, testY = build_dataset(test_set, seq_length)
print("#"*100)
lastX = last_set
print(lastX)

# input place holders
X = tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y = tf.placeholder(tf.float32, [None, 1])

# build a LSTM network
cell = tf.nn.rnn_cell.LSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=tf.tanh)
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn=None)  # We use the last cell's output

# cost/loss
loss = tf.reduce_sum(tf.square(Y_pred - Y))  # sum of the squares
# optimizer
optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)

# RMSE
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets - predictions)))

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

    # Training step
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={X: trainX, Y: trainY})
        print("[step: {}] loss: {}".format(i, step_loss))

    # Test step
    test_predict = sess.run(Y_pred, feed_dict={X: testX})
    print("test_predict:{}".format(test_predict))
    rmse_val = sess.run(rmse, feed_dict={targets: testY, predictions: test_predict})
    
    
    # Predictions test
    prediction_last = sess.run(Y_pred, feed_dict={X: lastX.reshape(1,seq_length,data_dim)})

print("step_loss: {}".format(step_loss),file = f)
print("RMSE: {}\n".format(rmse_val),file = f)
print("step_loss: {}".format(step_loss))
print("predictions ", end='')
print("RMSE: {}\n".format(rmse_val))
print("prediction_last :{}". format(prediction_last) )
df1 = ((testY * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df1 = pd.DataFrame(df1)
testY = df1[4]
df2 = ((test_predict * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df2= pd.DataFrame(df2)
pred = df2[4]
df = pd.concat([test_pred,testY], axis=1)
df.columns=['Pred','True']
df

주식이름을 입력하세요 : hrs


In [73]:
df2 = ((test_predict * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df2= pd.DataFrame(df2)
pred = df2[4]
test_pred

0     3200
1     3208
2     3226
3     3155
4     3100
5     3034
6     3007
7     2993
8     2948
9     2916
10    2970
11    3190
12    3193
Name: 4, dtype: int32

In [80]:
df = pd.concat([test_pred,testY], axis=1)
df.columns=['Pred','True']
df

Pred  True
0   3200  3175
1   3208  3170
2   3226  3170
3   3155  3165
4   3100  3195
5   3034  3180
6   3007  3145
7   2993  3135
8   2948  3165
9   2916  3180
10  2970  3090
11  3190  3110
12  3193  3055

In [68]:
df1 = ((testY * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df1 = pd.DataFrame(df1)
testY = df1[4]
testY

0     3175
1     3170
2     3170
3     3165
4     3195
5     3180
6     3145
7     3135
8     3165
9     3180
10    3090
11    3110
12    3055
Name: 4, dtype: int32

In [66]:
xy

array([[ 2850,  2890,  2840, 20472,  2840],
       [ 2830,  2845,  2795, 26542,  2840],
       [ 2830,  2835,  2760, 35375,  2835],
       [ 2850,  2880,  2825, 16935,  2850],
       [ 2840,  2885,  2840, 12976,  2850],
       [ 2855,  2940,  2855, 51621,  2920],
       [ 2920,  2945,  2905, 28694,  2945],
       [ 2970,  2970,  2905, 31441,  2935],
       [ 2950,  2995,  2925, 29935,  2950],
       [ 2950,  2975,  2940, 11938,  2975],
       [ 2975,  3025,  2965, 57832,  2980],
       [ 2990,  2990,  2930, 63395,  2930],
       [ 2970,  2970,  2925, 49889,  2950],
       [ 2955,  3015,  2950, 80597,  3015],
       [ 3005,  3110,  3005, 84388,  3060],
       [ 3060,  3120,  3015, 66504,  3120],
       [ 3135,  3135,  3085, 58016,  3090],
       [ 3100,  3110,  3075, 33766,  3080],
       [ 3080,  3120,  3050, 60633,  3120],
       [ 3080,  3115,  3075, 20191,  3080],
       [ 3080,  3120,  3050, 58634,  3070],
       [ 3110,  3120,  3060, 59869,  3080],
       [ 3100,  3100,  3045, 434

In [58]:
df2

0     3189
1     3210
2     3212
3     3197
4     3181
5     3144
6     3151
7     3142
8     3119
9     3101
10    3166
11    3198
12    3190
Name: 4, dtype: int32

In [59]:
df3 = df2[df2.index > 2 ]
df3

3     3197
4     3181
5     3144
6     3151
7     3142
8     3119
9     3101
10    3166
11    3198
12    3190
Name: 4, dtype: int32

In [33]:
      [ 3150,  3190,  3130, 72114,  3175],
       [ 3200,  3200,  3150, 43041,  3170],
       [ 3170,  3205,  3170, 31796,  3170],
       [ 3175,  3185,  3140, 20440,  3165],
       [ 3190,  3205,  3135, 44225,  3195],
       [ 3195,  3200,  3150, 14239,  3180],
       [ 3180,  3195,  3140, 28015,  3145],
       [ 3145,  3160,  3135, 21174,  3135],
       [ 3175,  3195,  3135, 79438,  3165],
       [ 3170,  3180,  3125, 66385,  3180],
       [ 3180,  3195,  3040, 59660,  3090],
       [ 3090,  3150,  3085, 20973,  3110],
       [ 3120,  3120,  3025, 27146,  3055]], dtype=int64)

array([[ 2850,  2890,  2840, 20472,  2840],
       [ 2830,  2845,  2795, 26542,  2840],
       [ 2830,  2835,  2760, 35375,  2835],
       [ 2850,  2880,  2825, 16935,  2850],
       [ 2840,  2885,  2840, 12976,  2850],
       [ 2855,  2940,  2855, 51621,  2920],
       [ 2920,  2945,  2905, 28694,  2945],
       [ 2970,  2970,  2905, 31441,  2935],
       [ 2950,  2995,  2925, 29935,  2950],
       [ 2950,  2975,  2940, 11938,  2975],
       [ 2975,  3025,  2965, 57832,  2980],
       [ 2990,  2990,  2930, 63395,  2930],
       [ 2970,  2970,  2925, 49889,  2950],
       [ 2955,  3015,  2950, 80597,  3015],
       [ 3005,  3110,  3005, 84388,  3060],
       [ 3060,  3120,  3015, 66504,  3120],
       [ 3135,  3135,  3085, 58016,  3090],
       [ 3100,  3110,  3075, 33766,  3080],
       [ 3080,  3120,  3050, 60633,  3120],
       [ 3080,  3115,  3075, 20191,  3080],
       [ 3080,  3120,  3050, 58634,  3070],
       [ 3110,  3120,  3060, 59869,  3080],
       [ 3100,  3100,  3045, 434

In [13]:
xy = df.values
seq_length = 5
train_size = int(len(xy) * 0.7)
train_set = xy[0:train_size]
test_set = xy[train_size - seq_length:]  # Index from [train_size - seq_length] to utilize past sequence
last_set = xy[-seq_length:,:]
display(xy)

array([[ 2850,  2890,  2840, 20472,  2840],
       [ 2830,  2845,  2795, 26542,  2840],
       [ 2830,  2835,  2760, 35375,  2835],
       [ 2850,  2880,  2825, 16935,  2850],
       [ 2840,  2885,  2840, 12976,  2850],
       [ 2855,  2940,  2855, 51621,  2920],
       [ 2920,  2945,  2905, 28694,  2945],
       [ 2970,  2970,  2905, 31441,  2935],
       [ 2950,  2995,  2925, 29935,  2950],
       [ 2950,  2975,  2940, 11938,  2975],
       [ 2975,  3025,  2965, 57832,  2980],
       [ 2990,  2990,  2930, 63395,  2930],
       [ 2970,  2970,  2925, 49889,  2950],
       [ 2955,  3015,  2950, 80597,  3015],
       [ 3005,  3110,  3005, 84388,  3060],
       [ 3060,  3120,  3015, 66504,  3120],
       [ 3135,  3135,  3085, 58016,  3090],
       [ 3100,  3110,  3075, 33766,  3080],
       [ 3080,  3120,  3050, 60633,  3120],
       [ 3080,  3115,  3075, 20191,  3080],
       [ 3080,  3120,  3050, 58634,  3070],
       [ 3110,  3120,  3060, 59869,  3080],
       [ 3100,  3100,  3045, 434

In [14]:
display(train_set)
train_set.shape

array([[ 2850,  2890,  2840, 20472,  2840],
       [ 2830,  2845,  2795, 26542,  2840],
       [ 2830,  2835,  2760, 35375,  2835],
       [ 2850,  2880,  2825, 16935,  2850],
       [ 2840,  2885,  2840, 12976,  2850],
       [ 2855,  2940,  2855, 51621,  2920],
       [ 2920,  2945,  2905, 28694,  2945],
       [ 2970,  2970,  2905, 31441,  2935],
       [ 2950,  2995,  2925, 29935,  2950],
       [ 2950,  2975,  2940, 11938,  2975],
       [ 2975,  3025,  2965, 57832,  2980],
       [ 2990,  2990,  2930, 63395,  2930],
       [ 2970,  2970,  2925, 49889,  2950],
       [ 2955,  3015,  2950, 80597,  3015],
       [ 3005,  3110,  3005, 84388,  3060],
       [ 3060,  3120,  3015, 66504,  3120],
       [ 3135,  3135,  3085, 58016,  3090],
       [ 3100,  3110,  3075, 33766,  3080],
       [ 3080,  3120,  3050, 60633,  3120],
       [ 3080,  3115,  3075, 20191,  3080],
       [ 3080,  3120,  3050, 58634,  3070],
       [ 3110,  3120,  3060, 59869,  3080],
       [ 3100,  3100,  3045, 434

(28, 5)

In [15]:
display(test_set)
test_set.shape

array([[ 3035,  3105,  3035, 51925,  3100],
       [ 3100,  3140,  3085, 55036,  3125],
       [ 3125,  3145,  3110, 44068,  3125],
       [ 3100,  3175,  3100, 85398,  3170],
       [ 3185,  3200,  3140, 56233,  3150],
       [ 3150,  3190,  3130, 72114,  3175],
       [ 3200,  3200,  3150, 43041,  3170],
       [ 3170,  3205,  3170, 31796,  3170],
       [ 3175,  3185,  3140, 20440,  3165],
       [ 3190,  3205,  3135, 44225,  3195],
       [ 3195,  3200,  3150, 14239,  3180],
       [ 3180,  3195,  3140, 28015,  3145],
       [ 3145,  3160,  3135, 21174,  3135],
       [ 3175,  3195,  3135, 79438,  3165],
       [ 3170,  3180,  3125, 66385,  3180],
       [ 3180,  3195,  3040, 59660,  3090],
       [ 3090,  3150,  3085, 20973,  3110],
       [ 3120,  3120,  3025, 27146,  3055]], dtype=int64)

(18, 5)

In [16]:
display(last_set)
last_set.shape

array([[ 3175,  3195,  3135, 79438,  3165],
       [ 3170,  3180,  3125, 66385,  3180],
       [ 3180,  3195,  3040, 59660,  3090],
       [ 3090,  3150,  3085, 20973,  3110],
       [ 3120,  3120,  3025, 27146,  3055]], dtype=int64)

(5, 5)

In [37]:
from __future__ import print_function
import pandas as pd
import numpy as np
import sqlalchemy


engine = sqlalchemy.create_engine('mysql+pymysql://kkang:leaf2027@localhost/stock?charset=utf8',encoding='utf-8')
    
name = input('주식이름을 입력하세요 : ')
date = input("날짜를 입력하세요 sample: '2019-01-10':")
        
select_query = "select * from market where Name= "
date_query = "Date > "

var = select_query +"'"+name+"'"+" "+"&&"+" "+date_query+"'"+date+"'"

df = pd.read_sql(var ,engine)
df = df[['Open','High','Low','Volume','Close']]

xy = df.values

seq_length = 5
data_dim = 5
hidden_dim = 10
output_dim = 1
learning_rate = 0.01
iterations = 1000


train_size = int(len(xy) * 0.7)
train_set = xy[0:train_size]
test_set = xy[train_size - seq_length:]  # Index from [train_size - seq_length] to utilize past sequence
last_set = xy[-seq_length:,:]

# build datasets
def build_dataset(time_series, seq_length):
    dataX = []
    dataY = []
    for i in range(0, len(time_series) - seq_length):
        _x = time_series[i:i + seq_length, :]
        _y = time_series[i + seq_length, [-1]]  # Next close price
        print(_x, "->", _y)
        dataX.append(_x)
        dataY.append(_y)
    return np.array(dataX), np.array(dataY)

trainX, trainY = build_dataset(train_set, seq_length)
print("#"*100)
testX, testY = build_dataset(test_set, seq_length)
print("#"*100)
lastX = last_set
print(lastX)

주식이름을 입력하세요 : hrs
날짜를 입력하세요 sample: '2019-01-10':2019-02-01
[[ 3035  3105  3035 51925  3100]
 [ 3100  3140  3085 55036  3125]
 [ 3125  3145  3110 44068  3125]
 [ 3100  3175  3100 85398  3170]
 [ 3185  3200  3140 56233  3150]] -> [3175]
[[ 3100  3140  3085 55036  3125]
 [ 3125  3145  3110 44068  3125]
 [ 3100  3175  3100 85398  3170]
 [ 3185  3200  3140 56233  3150]
 [ 3150  3190  3130 72114  3175]] -> [3170]
[[ 3125  3145  3110 44068  3125]
 [ 3100  3175  3100 85398  3170]
 [ 3185  3200  3140 56233  3150]
 [ 3150  3190  3130 72114  3175]
 [ 3200  3200  3150 43041  3170]] -> [3170]
[[ 3100  3175  3100 85398  3170]
 [ 3185  3200  3140 56233  3150]
 [ 3150  3190  3130 72114  3175]
 [ 3200  3200  3150 43041  3170]
 [ 3170  3205  3170 31796  3170]] -> [3165]
[[ 3185  3200  3140 56233  3150]
 [ 3150  3190  3130 72114  3175]
 [ 3200  3200  3150 43041  3170]
 [ 3170  3205  3170 31796  3170]
 [ 3175  3185  3140 20440  3165]] -> [3195]
[[ 3150  3190  3130 72114  3175]
 [ 3200  3200  3150 43041  

In [40]:
print(xy.shape)
xy

(18, 5)


array([[ 3035,  3105,  3035, 51925,  3100],
       [ 3100,  3140,  3085, 55036,  3125],
       [ 3125,  3145,  3110, 44068,  3125],
       [ 3100,  3175,  3100, 85398,  3170],
       [ 3185,  3200,  3140, 56233,  3150],
       [ 3150,  3190,  3130, 72114,  3175],
       [ 3200,  3200,  3150, 43041,  3170],
       [ 3170,  3205,  3170, 31796,  3170],
       [ 3175,  3185,  3140, 20440,  3165],
       [ 3190,  3205,  3135, 44225,  3195],
       [ 3195,  3200,  3150, 14239,  3180],
       [ 3180,  3195,  3140, 28015,  3145],
       [ 3145,  3160,  3135, 21174,  3135],
       [ 3175,  3195,  3135, 79438,  3165],
       [ 3170,  3180,  3125, 66385,  3180],
       [ 3180,  3195,  3040, 59660,  3090],
       [ 3090,  3150,  3085, 20973,  3110],
       [ 3120,  3120,  3025, 27146,  3055]], dtype=int64)

In [41]:
print(train_set)
train_set.shape

[[ 3035  3105  3035 51925  3100]
 [ 3100  3140  3085 55036  3125]
 [ 3125  3145  3110 44068  3125]
 [ 3100  3175  3100 85398  3170]
 [ 3185  3200  3140 56233  3150]
 [ 3150  3190  3130 72114  3175]
 [ 3200  3200  3150 43041  3170]
 [ 3170  3205  3170 31796  3170]
 [ 3175  3185  3140 20440  3165]
 [ 3190  3205  3135 44225  3195]
 [ 3195  3200  3150 14239  3180]
 [ 3180  3195  3140 28015  3145]]


(12, 5)

In [42]:
print(test_set)
test_set.shape

[[ 3170  3205  3170 31796  3170]
 [ 3175  3185  3140 20440  3165]
 [ 3190  3205  3135 44225  3195]
 [ 3195  3200  3150 14239  3180]
 [ 3180  3195  3140 28015  3145]
 [ 3145  3160  3135 21174  3135]
 [ 3175  3195  3135 79438  3165]
 [ 3170  3180  3125 66385  3180]
 [ 3180  3195  3040 59660  3090]
 [ 3090  3150  3085 20973  3110]
 [ 3120  3120  3025 27146  3055]]


(11, 5)

In [43]:
last_set

array([[ 3175,  3195,  3135, 79438,  3165],
       [ 3170,  3180,  3125, 66385,  3180],
       [ 3180,  3195,  3040, 59660,  3090],
       [ 3090,  3150,  3085, 20973,  3110],
       [ 3120,  3120,  3025, 27146,  3055]], dtype=int64)

In [44]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

test_min = np.min(xy, 0)
test_max = np.max(xy, 0)
test_denom = test_max - test_min

dataset = MinMaxScaler(xy)


In [45]:
print(dataset.shape)
dataset

(18, 5)


array([[0.        , 0.        , 0.06896552, 0.52960272, 0.32142857],
       [0.39393939, 0.35      , 0.4137931 , 0.57332172, 0.5       ],
       [0.54545455, 0.4       , 0.5862069 , 0.41918802, 0.5       ],
       [0.39393939, 0.7       , 0.51724138, 1.        , 0.82142857],
       [0.90909091, 0.95      , 0.79310345, 0.5901432 , 0.67857143],
       [0.6969697 , 0.85      , 0.72413793, 0.81331947, 0.85714286],
       [1.        , 0.95      , 0.86206896, 0.40475555, 0.82142857],
       [0.81818182, 1.        , 1.        , 0.24672916, 0.82142857],
       [0.84848485, 0.8       , 0.79310345, 0.08714288, 0.78571429],
       [0.93939394, 1.        , 0.75862069, 0.42139434, 1.        ],
       [0.96969697, 0.95      , 0.86206896, 0.        , 0.89285714],
       [0.87878788, 0.9       , 0.79310345, 0.19359463, 0.64285714],
       [0.66666667, 0.55      , 0.75862069, 0.09745781, 0.57142857],
       [0.84848485, 0.9       , 0.75862069, 0.9162439 , 0.78571429],
       [0.81818182, 0.75      , 0.

In [48]:
print(dataset[0][:])
df2 = ((dataset[0][:] * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df2

[0.         0.         0.06896552 0.52960272 0.32142857]


array([ 3035,  3105,  3035, 51925,  3100])

In [49]:
print(dataset[0][4])

0.3214285711989796


In [50]:
df2 = ((dataset[0][4] * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df2

array([ 3088,  3137,  3071, 37111,  3100])

In [51]:
df2 = ((dataset[17][4] * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df2

array([ 3035,  3105,  3025, 14239,  3055])

In [52]:
df2 = ((dataset[17][0] * ((test_max - test_min) + 1e-7) + test_min).astype(int))
df2

array([ 3120,  3156,  3099, 50896,  3127])